name: 'Rio CLI'
description: 'Use Rancher Labs Rio CLI to deploy to Kubernetes. See https://github.com/burmis/rio-github-action'
author: 'Mark Bennett'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  rio-cli-args:  # id of input
    description: 'Arguments to pass to the rio CLI.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.rio-cli-args }}