name: 'Rio CLI'
description: 'Use Rancher Labs Rio CLI to deploy to Kubernetes. See https://github.com/burmis/rio-github-action'
author: 'Mark Bennett'
branding:
  icon: 'cloud'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
